spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:5173"
                  - "https://c63060250848.ngrok-free.app"
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: true

          routes:
            - id: msvc-users
              uri: lb://msvc-users
              predicates:
                - Path=/users/**
            - id: auth
              uri: lb://msvc-users
              predicates:
                - Path=/auth/**
            - id: msvc-rooms
              uri: lb://msvc-rooms
              predicates:
                - Path=/rooms/**
            - id: msvc-hotels
              uri: lb://msvc-hotels
              predicates:
                - Path=/hotels/**
            - id: msvc-reservations
              uri: lb://msvc-reservations
              predicates:
                - Path=/reservations/**
            - id: msvc-payments
              uri: lb://msvc-payments
              predicates:
                - Path=/payment/**
            - id: msvc-reviews
              uri: lb://msvc-reviews
              predicates:
                - Path=/review/**



