server:
  port: ${GATEWAY_PORT:8090}

spring:
  application:
    name: msvc-api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: ${ALLOWED_ORIGINS:"http://localhost:5173"}
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: true

      routes:
        - id: msvc-users
          uri: lb://msvc-users
          predicates:
            - Path=/users/**
        - id: auth
          uri: lb://msvc-users
          predicates:
            - Path=/auth/**
        - id: msvc-rooms
          uri: lb://msvc-rooms
          predicates:
            - Path=/rooms/**
        - id: msvc-hotels
          uri: lb://msvc-hotels
          predicates:
            - Path=/hotels/**
        - id: msvc-reservations
          uri: lb://msvc-reservations
          predicates:
            - Path=/reservations/**
        - id: msvc-payments
          uri: lb://msvc-payments
          predicates:
            - Path=/payment/**
        - id: msvc-reviews
          uri: lb://msvc-reviews
          predicates:
            - Path=/review/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

security:
  jwt:
    secret: ${JWT_SECRET}
    user:
      generator: ${JWT_GENERATOR}



